---
#### Master1 and Master2 details required below can be obtained while running the mysql setup playbbok  #####

- hosts: '{{ hostgroup }}'
  become: yes
  vars:
  - mysql_root_pass: "admin"
  vars_prompt:
  - name: "hostgroup"
    prompt: "Enter the hostgroup"
    private: false
    default: testhost
  - name: "master1"
    prompt: "Enter master1 IP"
    private: false
    default: 1.1.1.1
  - name: "logfile1"
    prompt: "Enter master1 log file"
    private: false
    default: mysql-bin.000001
  - name: "logpos1"
    prompt: "Enter master1 logpos"
    private: false
    default: 154
  - name: "master2"
    prompt: "Enter master2 IP"
    private: false
    default: 2.2.2.2
  - name: "logfile2"
    prompt: "Enter master2 log file"
    private: false
    default: mysql-bin.000001
  - name: "logpos2"
    prompt: "Enter master2 logpos"
    private: false
    default: 167
 
  tasks:
  - name: create replica user on master1 and master2
    mysql_user:
      login_user: root
      login_password: admin
      name: replicator
      password: replicator1234
      priv: "*.*:REPLICATION SLAVE" 
      state: present

  - name: Stop slave on master2
    mysql_replication:
       login_user: root
       login_password: admin
       mode: stopslave
    when: inventory_hostname == "master2"

  - name: set master on master2
    mysql_replication:
       login_user: root
       login_password: admin
       mode: changemaster
       master_user: replicator
       master_password: replication1234
       master_host: "{{ master1 }}"
       master_log_file: "{{ logfile1 }}"
       master_log_pos: "{{ logpos1 }}"
    when: inventory_hostname == "master2"

  - name: Start slave on master2
    mysql_replication:
       login_user: root
       login_password: admin
       mode: startslave
    when: inventory_hostname == "master2"
 
  - name: Stop slave on master1
    mysql_replication:
       login_user: root
       login_password: admin
       mode: stopslave
    when: inventory_hostname == "master1"

  - name: set master on master1
    mysql_replication:
       login_user: root
       login_password: admin
       mode: changemaster
       master_user: replicator
       master_password: replication1234
       master_host: "{{ master2 }}"
       master_log_file: "{{ logfile2 }}"
       master_log_pos: "{{ logpos2 }}"
    when: inventory_hostname == "master1"

  - name: Start slave on master1
    mysql_replication:
       login_user: root
       login_password: admin
       mode: startslave
    when: inventory_hostname == "master1"

  - name: Reboot master1
    reboot:
      reboot_timeout: 120
    when: inventory_hostname == "master1"

  - name: Reboot master2
    reboot:
      reboot_timeout: 120
    when: inventory_hostname == "master2"
