---
- hosts: "{{ hostgroup }}"
  become: yes


  tasks:
  - name: Add user
    user:
      name: taskuser
      comment: taskuser user
      shell: /bin/bash
      generate_ssh_key: yes
      ssh_key_file: .ssh/taskuser
